import fs from "fs";

const out = process.argv[2] || "index.html";
const html = [
  "<!DOCTYPE html>",
  '<html lang="ko">',
  "<head>",
  '  <meta charset="UTF-8" />',
  '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
  "  <title>" + "\uC6B0\uC5F4 \uC571 \uC544\uC774\uCF58 \uBBF8\uB9AC\uBCF4\uAE30" + "</title>",
  "  <style>",
  "    * { box-sizing: border-box; margin: 0; padding: 0; }",
  "    body {",
  "      min-height: 100vh; display: grid; place-items: center;",
  "      background: #111;",
  "      font-family: -apple-system, BlinkMacSystemFont, 'Apple SD Gothic Neo', 'Noto Sans KR', sans-serif;",
  "      color: #fff;",
  "      padding: 24px;",
  "    }",
  "    .wrap { text-align: center; }",
  "    .phone {",
  "      width: 360px; height: 740px; border-radius: 44px;",
  "      background: linear-gradient(165deg, #0b1c3a 0%, #1a3a6b 45%, #0e284f 100%);",
  "      padding: 54px 28px 36px; position: relative;",
  "      box-shadow: 0 30px 80px rgba(0,0,0,.55);",
  "      overflow: hidden;",
  "      margin: 0 auto;",
  "    }",
  "    .phone::before {",
  "      content: ''; position: absolute; top: 14px; left: 50%; transform: translateX(-50%);",
  "      width: 110px; height: 28px; background: #0a0a0a; border-radius: 20px;",
  "    }",
  "    .status {",
  "      display: flex; justify-content: space-between; font-size: 13px; font-weight: 600;",
  "      opacity: .9; margin-bottom: 28px; padding: 0 4px;",
  "    }",
  "    .grid {",
  "      display: grid; grid-template-columns: repeat(4, 1fr); gap: 18px 12px;",
  "      justify-items: center;",
  "    }",
  "    .app { width: 64px; text-align: center; }",
  "    .app .icon {",
  "      width: 60px; height: 60px; border-radius: 14px;",
  "      background: rgba(255,255,255,.12); margin: 0 auto 6px;",
  "    }",
  "    .app .label { font-size: 11px; opacity: .75; }",
  "    .app.target .icon {",
  "      background: transparent; padding: 0; overflow: hidden;",
  "      box-shadow: 0 8px 20px rgba(0,123,255,.45);",
  "      outline: 2px solid rgba(255,255,255,.9); outline-offset: 3px;",
  "    }",
  "    .app.target img { width: 100%; height: 100%; object-fit: cover; display: block; }",
  "    .app.target .label { opacity: 1; font-weight: 700; }",
  "    .dock {",
  "      position: absolute; left: 20px; right: 20px; bottom: 28px;",
  "      height: 84px; border-radius: 28px; background: rgba(255,255,255,.14);",
  "      display: flex; align-items: center; justify-content: space-around; padding: 0 16px;",
  "    }",
  "    .dock .icon { width: 54px; height: 54px; border-radius: 14px; background: rgba(255,255,255,.18); }",
  "    h1 { margin-top: 22px; font-size: 18px; font-weight: 700; }",
  "    p { margin-top: 8px; font-size: 13px; opacity: .65; }",
  "    .big { margin-top: 28px; }",
  "    .big img { width: 140px; height: 140px; border-radius: 32px; display: block; margin: 0 auto;",
  "      box-shadow: 0 16px 40px rgba(0,0,0,.4); }",
  "    .big .cap { margin-top: 10px; font-size: 12px; opacity: .7; }",
  "  </style>",
  "</head>",
  "<body>",
  '  <div class="wrap">',
  '    <div class="phone">',
  '      <div class="status"><span>9:41</span><span>5G 100%</span></div>',
  '      <div class="grid">',
  '        <div class="app"><div class="icon"></div><div class="label">Safari</div></div>',
  '        <div class="app"><div class="icon"></div><div class="label">Photos</div></div>',
  '        <div class="app"><div class="icon"></div><div class="label">Maps</div></div>',
  '        <div class="app"><div class="icon"></div><div class="label">Music</div></div>',
  '        <div class="app"><div class="icon"></div><div class="label">Notes</div></div>',
  '        <div class="app target"><div class="icon"><img src="app_icon.png" alt="" /></div><div class="label">' +
    "\uC6B0\uC5F4" +
    "</div></div>",
  '        <div class="app"><div class="icon"></div><div class="label">Clock</div></div>',
  '        <div class="app"><div class="icon"></div><div class="label">Settings</div></div>',
  "      </div>",
  '      <div class="dock"><div class="icon"></div><div class="icon"></div><div class="icon"></div><div class="icon"></div></div>',
  "    </div>",
  "    <h1>" + "\uD648 \uD654\uBA74\uC5D0\uC11C \uBCF4\uC774\uB294 \uC571 \uC544\uC774\uCF58" + "</h1>",
  "    <p>" +
    "\uD655\uC778 \uD6C4 '\uBC18\uC601\uD574\uC918'\uB77C\uACE0 \uD558\uC2DC\uBA74 \uC571\uC5D0 \uB123\uC2B5\uB2C8\uB2E4" +
    "</p>",
  '    <div class="big">',
  '      <img src="app_icon.png" alt="" />',
  '      <div class="cap">' + "\uD070 \uC0AC\uC774\uC988" + "</div>",
  "    </div>",
  "  </div>",
  "</body>",
  "</html>",
  "",
].join("\n");

fs.writeFileSync(out, html, "utf8");
console.log("OK");
