#!/usr/bin/env bash
# .env.local 의 KAKAO_NATIVE_APP_KEY 를 Android/iOS 네이티브 설정에 반영합니다.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${ROOT}/.env.local"
ANDROID_PROPS="${ROOT}/flutter_app/android/local.properties"
IOS_XCCONFIG="${ROOT}/flutter_app/ios/Flutter/Kakao.xcconfig"

load_env_var() {
  local key="$1"
  local file="$2"
  [[ -f "$file" ]] || return 0
  local line
  line="$(grep -E "^${key}=" "$file" | tail -1 || true)"
  [[ -n "$line" ]] || return 0
  printf '%s' "${line#*=}"
}

KAKAO_KEY="$(load_env_var KAKAO_NATIVE_APP_KEY "$ENV_FILE")"

if [[ -z "$KAKAO_KEY" ]]; then
  echo "⚠ KAKAO_NATIVE_APP_KEY 가 .env.local 에 없습니다."
  echo "  카카오 개발자 콘솔에서 Native App Key 를 발급한 뒤 .env.local 에 추가하세요."
  KAKAO_SCHEME="kakao_not_configured"
else
  KAKAO_SCHEME="kakao${KAKAO_KEY}"
  echo "✓ KAKAO_NATIVE_APP_KEY 동기화 (${#KAKAO_KEY}자)"
fi

touch "$ANDROID_PROPS"
if grep -q '^kakao.nativeAppKey=' "$ANDROID_PROPS" 2>/dev/null; then
  if [[ "$(uname)" == Darwin ]]; then
    sed -i '' "s/^kakao.nativeAppKey=.*/kakao.nativeAppKey=${KAKAO_KEY}/" "$ANDROID_PROPS"
  else
    sed -i "s/^kakao.nativeAppKey=.*/kakao.nativeAppKey=${KAKAO_KEY}/" "$ANDROID_PROPS"
  fi
else
  printf '\nkakao.nativeAppKey=%s\n' "$KAKAO_KEY" >>"$ANDROID_PROPS"
fi

mkdir -p "$(dirname "$IOS_XCCONFIG")"
cat >"$IOS_XCCONFIG" <<EOF
// Generated by scripts/sync-kakao-native.sh — do not edit by hand.
KAKAO_APP_SCHEME=${KAKAO_SCHEME}
EOF

echo "  Android: flutter_app/android/local.properties"
echo "  iOS:     flutter_app/ios/Flutter/Kakao.xcconfig"
